spring.application.name=raspi-cloud-lab

management.endpoints.web.exposure.include=health,info,metrics

spring.datasource.url=jdbc:postgresql://postgres:5432/appdb
spring.datasource.username=admin
spring.datasource.password=admin

# Número MÁXIMO de conexões que o pool poderá abrir com o banco.
# Se todas estiverem em uso, novas requests precisarão esperar.
# Muito alto = consumo excessivo de RAM/CPU no PostgreSQL.
# Muito baixo = filas e lentidão sob carga.
spring.datasource.hikari.maximum-pool-size=10


# Quantidade MÍNIMA de conexões ociosas que o pool tentará manter abertas.
# Mesmo sem tráfego, essas conexões ficam prontas para uso imediato.
# Ajuda a reduzir latência ao receber novas requests.
spring.datasource.hikari.minimum-idle=2


# Tempo máximo que uma conexão pode ficar OCIOSA no pool antes de ser fechada.
# Valor em milissegundos.
# Aqui: 30000 ms = 30 segundos.
# Serve para liberar recursos quando o sistema está sem uso.
spring.datasource.hikari.idle-timeout=30000


# Tempo máximo de vida de uma conexão, mesmo que ela esteja funcionando.
# Após esse tempo, o Hikari recicla a conexão criando outra nova.
# Valor em milissegundos.
# Aqui: 1800000 ms = 30 minutos.
# Isso evita conexões "zumbis", problemas de rede e conexões inválidas.
spring.datasource.hikari.max-lifetime=1800000


# Tempo máximo que uma request aguardará por uma conexão livre do pool.
# Se passar desse tempo e nenhuma conexão estiver disponível:
# -> exceção será lançada.
# Valor em milissegundos.
# Aqui: 30000 ms = 30 segundos.
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
